package com.fast.caixaMultibanco.recursos;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


@RestController
@RequestMapping(value = "/")
public class InicialController {


	@GetMapping
	public ResponseEntity<Object> paginaInicial() {
		return ResponseEntity.ok().body("<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "    <head>\r\n"
				+ "        <title>Caixa 24h</title>\r\n"
				+ "    </head>\r\n"
				+ "\r\n"
				+ "    <header>\r\n"
				+ "        <style type=\"text/css\">\r\n"
				+ "            .card{\r\n"
				+ "\r\n"
				+ "                border: 1px solid; \r\n"
				+ "                padding: 15px;\r\n"
				+ "                width: 720px;\r\n"
				+ "            }\r\n"
				+ "            .card h5{\r\n"
				+ "                color: #424242;\r\n"
				+ "            }\r\n"
				+ "            .card h5 span{\r\n"
				+ "                color: #FF8000;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "        </style>\r\n"
				+ "\r\n"
				+ "    </header>\r\n"
				+ "\r\n"
				+ "    <body>\r\n"
				+ "        <div> \r\n"
				+ "            <h1>Seja bem vindo ao Caixa Multibanco Eletrônico</h1>\r\n"
				+ "            <h3>\r\n"
				+ "                <p>Para começar faça login no seu banco</p>\r\n"
				+ "                Acesse atraves do Postman ou qualquer outro API Client\r\n"
				+ "            </h3>\r\n"
				+ "        </div>\r\n"
				+ "\r\n"
				+ "        <div class=\"card\" >\r\n"
				+ "            <h4 style=\"margin:0px\">Login: Com o metodo POST</h4>\r\n"
				+ "            <a href=\"https://caixa-24-accenture.herokuapp.com/banco/loginBanco\">banco/loginBanco</a>\r\n"
				+ "            <p>Exemplo de requisição: </p>\r\n"
				+ "            <h5>\r\n"
				+ "                {  <br>\r\n"
				+ "                    &nbsp; <span>\"login\"</span>: \"exemplo_login\",<br>\r\n"
				+ "                    &nbsp; <span>\"senha\"</span>: \"S3nh@.d0-Cl13nt3\", <br> \r\n"
				+ "                    &nbsp; <span>\"caixa\"</span>: 1,  <br>\r\n"
				+ "                    &nbsp; <span>\"conta\"</span>: \"Conta do Cliente\" <br>\r\n"
				+ "                }\r\n"
				+ "            </h5>\r\n"
				+ "        </div>\r\n"
				+ "\r\n"
				+ "        <div class=\"card\">\r\n"
				+ "            <h4 style=\"margin:0px\">Consultar Saldo: Com o metodo GET</h4>\r\n"
				+ "            <a href=\"https://caixa-24-accenture.herokuapp.com/banco/consultarSaldo\">banco/consultarSaldo</a>\r\n"
				+ "            <p>Exemplo de requisição: </p>\r\n"
				+ "            <h5>\r\n"
				+ "                {  <br>\r\n"
				+ "                   \r\n"
				+ "                    &nbsp; <span>\"acesso\"</span>: \"EDDA8F2DA1428C789F3D599432188D1B687BCCD18ECD02400498721AB4C60D59\" \r\n"
				+ "                 <br>\r\n"
				+ "                }   \r\n"
				+ "            </h5>\r\n"
				+ "        </div>\r\n"
				+ "\r\n"
				+ "        <div class=\"card\">\r\n"
				+ "            <h4 style=\"margin:0px\">Fazer Saque: Com o metodo POST</h4>\r\n"
				+ "            <a href=\"https://caixa-24-accenture.herokuapp.com/banco/fazerSaque\">banco/fazerSaque</a>\r\n"
				+ "            <p>Exemplo de requisição: </p>\r\n"
				+ "            <h5>\r\n"
				+ "                {  <br>\r\n"
				+ "                     &nbsp; <span>\"acesso\"</span>: \"EDDA8F2DA1428C789F3D599432188D1B687BCCD18ECD02400498721AB4C60D59\", <br>\r\n"
				+ "                     &nbsp; <span>\"valor\"</<span>span>: 10.0 <br>\r\n"
				+ "                }   \r\n"
				+ "            </h5>\r\n"
				+ "        </div>\r\n"
				+ "\r\n"
				+ "        <div class=\"card\">\r\n"
				+ "            <h4 style=\"margin:0px\">Alterar Dados: Com o metodo PUT</h4>\r\n"
				+ "            <a href=\"https://caixa-24-accenture.herokuapp.com/banco/alterarDadosConta\">banco/alterarDadosConta</a>\r\n"
				+ "            <p>Exemplo de requisição: </p>\r\n"
				+ "            <h5>\r\n"
				+ "                {  <br>\r\n"
				+ "                     &nbsp; <span>\"acesso\"</span>: \"EDDA8F2DA1428C789F3D599432188D1B687BCCD18ECD02400498721AB4C60D59\", <br>\r\n"
				+ "                     &nbsp; <span>\"nome_cliente\"</span>: \"nome do cliente\", <br>\r\n"
				+ "                     &nbsp; <span>\"telefone\"</span>: \"00 00000-0000\", <br>\r\n"
				+ "                }   \r\n"
				+ "            </h5>\r\n"
				+ "        </div>\r\n"
				+ "\r\n"
				+ "        <div class=\"card\">\r\n"
				+ "            <h4 style=\"margin:0px\">Consultar dados da conta: Com o metodo GET</h4>\r\n"
				+ "            <a href=\"https://caixa-24-accenture.herokuapp.com/banco/consultarDadosConta\">banco/consultarDadosConta</a>\r\n"
				+ "            <p>Exemplo de requisição: </p>\r\n"
				+ "            <h5>\r\n"
				+ "                {  \r\n"
				+ "                    <br>\r\n"
				+ "                   \r\n"
				+ "                    &nbsp; <span>\"acesso\"</span>: \"EDDA8F2DA1428C789F3D599432188D1B687BCCD18ECD02400498721AB4C60D59\" \r\n"
				+ "                 <br>\r\n"
				+ "                }   \r\n"
				+ "            </h5>\r\n"
				+ "        </div>\r\n"
				+ "\r\n"
				+ "    </body>\r\n"
				+ "</html>");		
	}
}
